### ISSUE TITLE
cyrillic in file name

### ISSUE THREAD

**Issue by nassl** [plk/biber#359] opened 2020-12-09 05:10 UTC
biber 2.15 doesn't understand russian in tex file name. For example the "пример.tex" give biber error, but the same tex file with name "ppp.tex" will correct for biber. This problem has abseny in early version of biber.

**Comment by moewew** [comment] 2020-12-09 07:16
On Windows 10 I get
```
C:\...>.\biber.exe пример
Can't open ??????.blg (Invalid argument) at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-fc05a18acb242b083d2335a96eac62a8c1c872aa\inc\lib/Log/Log4perl/Appender/File.pm line 151.
```
from both Biber 2.16 (dev) and the current 2.15 shipped in MikTeX.

A file name like `grüße.tex` works fine for me (from the command line and via TeXworks - with `latexmk` Biber is sent off to look for a garbage file name, but I think that is a `latexmk` issue).

A `.bib` file name like `пример.bib` is no problem as long as the `.tex` file has a name that works.

**Comment by plk** [comment] 2020-12-09 19:48
This is an issue with `Log4perl` - I've raised it with the developers.

**Comment by plk** [comment] 2020-12-10 16:14
You can use the `--logfile` option to specify a logfile name without Cyrillic to workaround this.

**Comment by nassl** [comment] 2020-12-11 06:35
> You can use the `--logfile` option to specify a logfile name without Cyrillic to workaround this.

Thanks, I use texstudio with next command:  biber % --logfile temp
but now I have:    ERROR - Cannot find 'Ð ÐµÐ·ÑÐ»ÑÑÐ°Ñ.bcf'!  
were Ð ÐµÐ·ÑÐ»ÑÑÐ°Ñ is Cyrillic filename of the tex-file.

**Comment by plk** [comment] 2020-12-11 19:42
Syntax should be:

```
biber --logfile=temp %
```

**Comment by moewew** [comment] 2020-12-12 13:07
On my Windows 10 machine
```
biber.exe --logfile temp пример 
```
avoids the
```
Can't open ??????.blg (Invalid argument) at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-fc05a18acb242b083d2335a96eac62a8c1c872aa\inc\lib/Log/Log4perl/Appender/File.pm line 151.
```
error from logging. But I get a similar problem when Biber tries to read the `.bcf`. `temp.blg` contains
```
[0] Config.pm:312> INFO - This is Biber 2.16 (beta)
[0] Config.pm:315> INFO - Logfile is 'temp.blg'
[181] biber-MSWIN64:332> INFO - === 
[495] Utils.pm:411> ERROR - Cannot find '??????.bcf'!
[495] Biber.pm:132> INFO - ERRORS: 1
```

**Comment by plk** [comment] 2020-12-12 20:24
I have found a way to completely fix all of these UTF-8 issues on (64-bit) windows with a patch to `runperl.c` and this works very nicely. However, packing with `PAR::Packer` doesn't seem to notice this as it presumably uses it's own wrapper into libperl and so I will discuss with the `PAR::Packer` maintainer as this fix would solve all of the UTF-8 issues in windows at a stroke.

**Comment by plk** [comment] 2020-12-16 16:19
After lots of discussions with various people, including the Perl developers, here is the status and some good news:

- The issue is deep and the perl team are looking at it but it won't be generally fixed for some time
- The `PAR::Packer` maintainer doesn't want to touch this until it's been fixed upstream in Perl
- I messed about a lot with `PAR:Packer` looking for a fix and found something which would likely work but would be a hack and probably not robust.
- Then I was pointed at the Windows 10 1803+ "Use Unicode UTF8 for worldwide language support" setting which, when enabled, switches most Windows APIs we care about to UTF-8  and this works very well. In testing, I am able to use Cyrillic .bcfs, logs etc. with no problems. There was one small fix to `biber` to nicely report the file names.
- I also added a new option to `biber` DEV `--winunicode` which you can use to disable all the UTF-16 messing about internally if you have enabled the Windows option. It doesn't seem to matter much whether you use this `biber` option at present but it does make `biber` use standard unicode calls internally instead of the special conditionals for Windows which should be generally more reliable, just in case there are edge cases.

Have a look at the latest `biber` DEV on SF and see how it works for you if you turn on that option in Windows. Most Windows 10 users have that option now since 1803 is nearly three years old. It can impact legacy apps that aren't UTF-8 aware though ...

**Comment by moewew** [comment] 2020-12-16 21:41
Mhhh, I tried the DEV version from SF.

`biber grüße` still fails
```
C:\Users\Moritz\Documents\TeX\zjample\Neuer Ordner>.\biber.exe grüße
INFO - This is Biber 2.16 (beta)
INFO - Logfile is 'gr��e.blg'
Wide character in print at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-e0d7f36271a2afe67ce28dba021670cfcf784db4\inc\lib/Log/Log4perl/Appender/Screen.pm line 41.
ERROR - Cannot find 'gr��e.bcf'!
INFO - ERRORS: 1    
```
`biber --logfile temp grüße`
```
C:\Users\Moritz\Documents\TeX\zjample\Neuer Ordner>.\biber.exe --logfile temp grüße
INFO - This is Biber 2.16 (beta)
INFO - Logfile is 'temp.blg'
Wide character in print at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-e0d7f36271a2afe67ce28dba021670cfcf784db4\inc\lib/Log/Log4perl/Appender/Screen.pm line 41.                                                                  ERROR - Cannot find 'gr��e.bcf'!
INFO - ERRORS: 1                                                                                                                                         
```
`biber пример`
```
C:\Users\Moritz\Documents\TeX\zjample\Neuer Ordner>.\biber.exe пример
Can't open ??????.blg (Invalid argument) at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-e0d7f36271a2afe67ce28dba021670cfcf784db4\inc\lib/Log/Log4perl/Appender/File.pm line 151.
```

My Windows 10 tells me it is version 2004 (build 19041.685), so I'm guessing the UTF-8 stuff should be available...

**Comment by moewew** [comment] 2020-12-16 21:52
Mhh, alright. I found https://support.microsoft.com/en-gb/help/4490392/apps-using-legacy-crts-don-t-work-properly-when-regional-setting-is-no and it turns out on my machine **Beta: Use Unicode UTF8 for worldwide language support** was disabled. Enabling this option indeed makes all of the examples above work. If I read the linked page properly it appears that Microsoft backed out of enabling this option by default, meaning that users would have to chase down the option and enable it explicitly...

`пример` still complains about two wide characters, but the resulting `.bbl` seems fine
```
C:\Users\Moritz\Documents\TeX\zjample\Neuer Ordner>.\biber.exe пример
INFO - This is Biber 2.16 (beta)
INFO - Logfile is 'пример.blg'
INFO - Reading 'пример.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file 'biblatex-examples.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source 'C:/Program Files/MiKTeX/bibtex/bib/biblatex/biblatex-examples.bib'
INFO - Overriding locale 'en-GB' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Overriding locale 'en-GB' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Sorting list 'nyt/global//global/global' of type 'entry' with template 'nyt' and locale 'en-GB'
INFO - No sort tailoring available for locale 'en-GB'
Wide character in print at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-e0d7f36271a2afe67ce28dba021670cfcf784db4\inc\lib/Log/Log4perl/Appender/Screen.pm line 41.
INFO - Writing 'пример.bbl' with encoding 'UTF-8'
Wide character in print at C:\Users\Moritz\AppData\Local\Temp\par-4d6f7269747a\cache-e0d7f36271a2afe67ce28dba021670cfcf784db4\inc\lib/Log/Log4perl/Appender/Screen.pm line 41.
INFO - Output to пример.bbl  
```

**Comment by plk** [comment] 2020-12-16 21:55
The wide character is the terminal encoding - that can be fixed by setting the powershell session to utf8 - it's nothing to do with `biber` per se. That option is still `beta` because too many apps don't handle UTF8 because they are used to it all being UTF-16 but eventually, it'll be default, I'm sure because the decision to use UTF-16 was just a legacy thing because UTF-8 wasn't available to MS at the time they moved to Unicode.

**Comment by plk** [comment] 2020-12-17 12:29
For compat with other OSes, I have changed it a little so that to get full UTF-8 compat on Windows with the Windows option enabled, you have to use the `--winunicode|W` biber option now.

**Comment by synalice** [comment] 2022-11-09 13:37
@plk, I would like this issue to be reopened. Biber still complains about not being able to find `.bcf` file after I've done what @moewew has suggested [here](https://github.com/plk/biber/issues/359#issuecomment-747063053). This error happens both with and without `--winunicode` flag set.

```powershell
PS C:\Users\User\Documents\Folder\Практическая работа №7> biber '.\Практическая работа №7'
INFO - This is Biber 2.18
INFO - Logfile is '.\ÐÑÐ°ÐºÑÐ¸ÑÐµÑÐºÐ°Ñ ÑÐ°Ð±Ð¾ÑÐ° â7.blg'
ERROR - Cannot find '.\Практическая работа №7.bcf'!
INFO - ERRORS: 1
```
```powershell
PS C:\Users\User\Documents\Информатика\Практическая работа №7> biber --logfile=temp '.\Практическая работа №7'
INFO - This is Biber 2.18
INFO - Logfile is 'temp.blg'
ERROR - Cannot find '.\Практическая работа №7.bcf'!
INFO - ERRORS: 1
```

And yes, the folder with the `.tex` file is named the same as the `.tex` file itself. Although I doubt that has anything to do with an error.

OS: Windows 10
OS Version: LTSC 21H2 
OS Builld: 19044.2193

**Comment by plk** [comment] 2022-11-09 13:42
Just to be clear - you have enabled UTF8 as the default in windows as mentioned above? Also, just to be sure, can you omit the `.\` from inside the quotes?

**Comment by moewew** [comment] 2022-11-10 07:12
@synalice You need to enable the UTF-8 thingy on Windows as described in my post, but as mentioned in https://github.com/plk/biber/issues/359#issuecomment-747410665 you also need to run Biber with the option `-W`.

```
> biber -W "Практическая работа №7"
```

**Comment by K-gihu** [comment] 2023-06-08 05:11
Here on Linux system also encountered similar problem when compiling file with Chinese filename. The .bbl file **CAN** be successfully generated but the echo is garbled, for example:
```shell
/tmp/test 
% biber tes中文t  
INFO - This is Biber 2.19
INFO - Logfile is 'tesä¸­æt.blg'
Wide character in print at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender/Screen.pm line 57.
INFO - Reading './tes中文t.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex file '~/mybibliography/bibliography.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source '/home/klu/mybibliography/bibliography.bib'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Sorting list 'none/global//global/global' of type 'entry' with template 'none' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'tes中文t.bbl' with encoding 'UTF-8'
INFO - Output to tes中文t.bbl
```

And using -W option or --logfile option mentioned above and solve this problem.

**Comment by plk** [comment] 2023-06-08 07:04
For display, that could well be the encoding of your terminal - what do you environment variables say for the LANG settings?

**Comment by K-gihu** [comment] 2023-06-10 02:06
> For display, that could well be the encoding of your terminal - what do you environment variables say for the LANG settings?

My LANG is zh_CN.UTF-8 and I also tried en_US.UTF-8 but that didn't help.
 ```shell
% printenv LANG
zh_CN.UTF-8

% biber tes中文t 
INFO - This is Biber 2.19
INFO - Logfile is 'tesä¸­æt.blg'
Wide character in print at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender/Screen.pm line 57.
INFO - Reading './tes中文t.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex file '~/mybibliography/bibliography.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source '/home/klu/mybibliography/bibliography.bib'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Sorting list 'none/global//global/global' of type 'entry' with template 'none' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'tes中文t.bbl' with encoding 'UTF-8'
INFO - Output to tes中文t.bbl

% LANG=en_US.UTF-8 biber tes中文t 
INFO - This is Biber 2.19
INFO - Logfile is 'tesä¸­æt.blg'
Wide character in print at /usr/share/perl5/vendor_perl/Log/Log4perl/Appender/Screen.pm line 57.
INFO - Reading './tes中文t.bcf'
INFO - Found 1 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex file '~/mybibliography/bibliography.bib' for section 0
INFO - LaTeX decoding ...
INFO - Found BibTeX data source '/home/klu/mybibliography/bibliography.bib'
INFO - Overriding locale 'en-US' defaults 'variable = shifted' with 'variable = non-ignorable'
INFO - Overriding locale 'en-US' defaults 'normalization = NFD' with 'normalization = prenormalized'
INFO - Sorting list 'none/global//global/global' of type 'entry' with template 'none' and locale 'en-US'
INFO - No sort tailoring available for locale 'en-US'
INFO - Writing 'tes中文t.bbl' with encoding 'UTF-8'
INFO - Output to tes中文t.bbl
```

**Comment by plk** [comment] 2023-06-10 14:58
Please try 2.20 DEV version from SourceForge - this should be fixed - the log file name screen logging was not dealing with UTF-8 properly.

**Comment by K-gihu** [comment] 2023-06-11 15:44
I have tried the development [version](https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/Linux/biber-linux_x86_64.tar.gz/download) and I can confirm that this is fixed. Thank you!

**Closed** 2023-06-11 15:46 UTC
