### ISSUE TITLE
Duplicate entries are removed and so missing in the next refsection

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#79] opened 2015-08-26 18:05 UTC
I have a document which uses two bib-files which can contain duplicate entries. 

~~~~~
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{biblatex}
\addbibresource{duplicate.bib}
\addbibresource{biblatex-examples.bib}

\begin{document}
\begin{refsection}[duplicate.bib,biblatex-examples.bib]
\cite{shore} \cite{herrmann}
\printbibliography
\end{refsection}

\begin{refsection}[biblatex-examples.bib]
\cite{shore}
\printbibliography
\end{refsection}
\end{document}
~~~~~

The entry `shore` is also in duplicate.bib (in reality the entries are identical):

~~~~~
@article{shore,
author={Author},
title={Blub},
year={2000}
}
~~~~~

When biber process the section 1 it discovers the duplicate and skips it:

~~~~~
[2565] Utils.pm:146> WARN - Duplicate entry key: 'shore' in file 'd:/texlive/2015/texmf-dist/bibtex/bib/biblatex/biblatex/biblatex-examples.bib', skipping ...
~~~~~

That's fine. But at section 2 the entry seems to be gone and now biber complains

~~~~~
[2656] Biber.pm:3115> INFO - Looking for bibtex format file 'biblatex-examples.bib' for section 2
[3188] Utils.pm:146> WARN - I didn't find a database entry for 'shore' (section 2)
~~~~~

And the second bibliography is empty. 

![duplicate](https://cloud.githubusercontent.com/assets/4047173/9501739/4f526cbe-4c2d-11e5-84e1-3017e89d4572.PNG)

**Comment by plk** [comment] 2015-08-26 18:48
What happens if you remove the addbibresource lines?

**Comment by u-fischer** [comment] 2015-08-26 19:04
This doesn't change anything.

**Comment by plk** [comment] 2015-08-27 13:50
The problem is that biber retains a map of data sources to entries and `shore` is removed from the map for `biblatex-examples.bib` as a duplicate and so it's there for the second refsection. If you do this, it works:

```
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{biblatex}

\begin{document}
\begin{refsection}[test4.bib, biblatex-examples.bib]
\cite{shore} \cite{herrmann}
\printbibliography
\end{refsection}

\begin{refsection}[test4.bib]
\cite{shore}
\printbibliography
\end{refsection}
\end{document}
```

**Comment by u-fischer** [comment] 2015-08-27 14:28
Yes, I understand why it happens and also know that the order matters and changes the behaviour. But the question is if it should/can be avoid? It doesn't feel right, that bib-files used in other refsections has such side-effects. 

Changing the order can also change the output: `\begin{refsection}[biblatex-examples.bib, duplicate.bib] ` will use the shore entry from the biblatex-examples.bib and not from duplicate.bib. As it can be that duplicate.bib contains some entries meant to *overwrite* entries from a general .bib this is perhaps not the wanted output. 

But the more problematic case is that it gets difficult to created a merged bibliography. Wenn one does something like the following author2 and author3 would loose the entries used by author1:

~~~~~
\begin{refsection}[author1.bib, author2.bib, author3.bib]
Complete Bibliography
...
\end{refsection}

\begin{refsection}[author1.bib]
Bibliography author 1
\end{refsection}

\begin{refsection}[author2.bib]
Bibliography author 2
\end{refsection}

\begin{refsection}[author3.bib]
Bibliography author 3
\end{refsection}

~~~~~~

Also while one can avoid the missing entry when only two bib-files are involved it could be impossible or difficult with more files and duplicates -- imho a case that is not improbable for journals.

**Comment by plk** [comment] 2015-08-27 14:38
Ok, this can be conditionalised with a biber "skipduplicates" option - what do you think?

**Comment by u-fischer** [comment] 2015-08-27 14:49
Sounds like a good idea. But naturally this shouldn't lead to double entries (or biblatex errors). So in my last examples, if author1.bib and author2.bib and author3.bib have an duplicate bib key, then the complete bibliographie should show only one instance (imho from author1.bib, a biber warning would be still useful so that the lector can check ...), while the other refsections should show the entries from their own .bib.

**Comment by plk** [comment] 2015-08-27 16:41
Ok, try biber 2.2 DEV from sourceforge. There is a new "noskipduplicates" option which does this. I tried your second example and it works as expected so far, using the duplicate from the local refsection.

**Comment by u-fischer** [comment] 2015-08-27 17:29
Works like a charm. This is the output of my test without the option (with the missing shore entries):

![dupmissing](https://cloud.githubusercontent.com/assets/4047173/9527843/b0bd6854-4cf1-11e5-86dc-ddfd00da7634.PNG)

And this with the option. Every refsection shows the correct entry (I added little differences to identify them):

![noskipdup](https://cloud.githubusercontent.com/assets/4047173/9527863/d59f42b4-4cf1-11e5-9e74-917277c27e46.PNG)

**Comment by plk** [comment] 2015-08-27 18:04
Good, I'll close this then - it will be in the next release.

**Closed by plk** 2015-08-27 18:04 UTC
