### ISSUE TITLE
Sorting ignores 'and others'/et al.

### ISSUE THREAD

**Issue by moewew** [plk/biber#177] opened 2017-07-29 13:02 UTC
Consider the following MWE

```
\documentclass{article}
\usepackage[style=authortitle,backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{A,
    author = {Gauck, Joachim},
    title = {Title A},
}

@book{B,
    author = {Gauck, Joachim and others},
    title = {Title B},
}

@book{C,
    author = {Gauck, Joachim},
    title = {Title C},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
   \cite{A,B,C}
   \printbibliography
\end{document}
``` 

The output is 
> Gauck, Joachim. _Title A._
Gauck, Joachim et al. _Title B._
Gauck, Joachim. _Title C._

This shows that `and others`/'et al.' is ignored for sorting purposes. This surprised me, especially seeing that in the `.bbl` the `namehash` etc. suggest that 'Gauck, Joachim' and 'Gauck, Joachim et al.' are two different authors.

BibTeX sorts 'Gauck, Joachim et al.' after 'Gauck, Joachim' which comes closer to what I would expect.

Would it be possible to either (1) always sort names with `and others` different from their non-`and other`'d counterpart, or (2) add an option to control whether to sort the two forms as the same or not?

This came up in https://tex.stackexchange.com/q/383838/35864

**Comment by plk** [comment] 2017-07-29 17:02
Amazing how this bug hasn't been noticed for so long - fixed in 2.8 DEV. Explicit "and others" will always sort after the same name list without it now. I can't see any case for wanting to sort them the same.

**Comment by moewew** [comment] 2017-07-29 18:39
Amazing indeed, I assume not many people use `and others`, though. Thanks for fixing this so quickly.

Can you have a look at 
```
\documentclass{article}

\usepackage[style=authortitle,backend=biber]{biblatex}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{A,
    author = {Gauck, Joachim and others},
    title = {Title A},
}

@book{B,
    author = {Gauck, Joachim and Anne Uthor and others},
    title = {Title B},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
   \cite{A,B}
   \printbibliography
\end{document}
```

When I run the MWE I get `\strng{namehash}{454483db35010328e8ef8cb2a6c3a62a}` for both entries even though the name lists are different and the truncation settings are such that the two lists are definitely distinct. The `fullhash` is of correctly distinct.

**Comment by plk** [comment] 2017-07-29 22:08
The problem is what to do with `and others` in terms of `maxnames` - does an explicit `and others` always exceed `maxnames`? That's what's happening here, it means `maxnames` is always exceeded and therefore it's truncating to `minnames` which is by default 1 and since `namehash` obeys truncation, they both end up with the same hash.

**Comment by moewew** [comment] 2017-07-30 06:21
Mhhh, but the output in citations and the bibliography of the two lists is the same. I would assume that `namehash` in a way obeys `maxnames`/`minnames` in the way that it gives the exact same result as in the document. 

At the moment the `namehash` for both 'Gauck et al.' and 'Gauck, Uthor, et al.' is the same. I don't think that can be right. Because the lists that identify the citations obeying `maxnames`/`minnames` and all other options are different.

Maybe `namehash` with explicit `and others` does not take into account `uniquelist`?

**Comment by plk** [comment] 2017-07-30 11:40
It's to do with how the visibility counter is calculated and explicit `and others` is a special override for this currently. I have to think about it.

**Comment by moewew** [comment] 2017-07-30 15:59
I get the same output in the document. I was talking about `namehash` in the `.bbl`. That is the same for both. 

Indeed, if I change the MWE to use `namehash` (instead of `fullhash`) for dashing,
```
\documentclass{article}

\usepackage[style=authortitle,backend=biber]{biblatex}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{A,
    author = {Gauck, Joachim and others},
    title = {Title A},
}

@book{B,
    author = {Gauck, Joachim and Anne Uthor and others},
    title = {Title B},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\makeatletter
\renewbibmacro*{bbx:savehash}{%
  \savefield{namehash}{\bbx@lasthash}}

\renewbibmacro*{bbx:dashcheck}[2]{%
  \ifboolexpr{
    test {\iffieldequals{namehash}{\bbx@lasthash}}
    and
    not test \iffirstonpage
    and
    (
       not bool {bbx@inset}
       or
       test {\iffieldequalstr{entrysetcount}{1}}
    )
  }
    {#1}
    {#2}}
\makeatother

\begin{document}
   \cite{A,B}
   \printbibliography
\end{document}
```
I obtain
> Gauck, Joachim et al. Title A.
— Title B.


showing that as far as `namehash` is concerned both lists are seen as the same.

**Comment by plk** [comment] 2017-07-30 17:22
I understand that but I don't quite see why it should be different and what the problem is since dashing uses `fullhash`.  Since `and others` forces `maxnames` to be exceeded, truncation is expected. If there is something which actually breaks, I am open to an option to set the default "length" of `and others`.

**Comment by moewew** [comment] 2017-07-30 17:54
OK, sorry for not being clear. I have now found an example that definitely shows undesirable behaviour.

Consider
```
\documentclass{article}

\usepackage[style=authortitle-icomp,backend=biber]{biblatex}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{A,
    author = {Gauck, Joachim and others},
    title = {Title A},
}

@book{B,
    author = {Gauck, Joachim and Anne Uthor and others},
    title = {Title B},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{A}

\cite{B}

\cite{A,B}
\end{document}
```
> Gauck et al., Title A
Gauck, Uthor, et al., Title B
Gauck et al., Title A, Title B

I would expect the last citation to read
> Gauck et al., Title A; Gauck, Uthor, et al., Title B

**Comment by plk** [comment] 2017-07-30 19:59
Ok, I see your point. Please try 2.8 DEV now.

**Comment by moewew** [comment] 2017-07-30 20:51
The examples from above work great now. Thank you.

Unfortunately, I have a new case
```
\documentclass{article}

\usepackage[style=authortitle-icomp,backend=biber,uniquelist=false,minnames=1,maxnames=1]{biblatex}

\usepackage{filecontents}

\begin{filecontents}{\jobname.bib}
@book{A,
    author = {Gauck, Joachim and Anne Uthor and others},
    title = {Title A},
}

@book{B,
    author = {Gauck, Joachim and Anne Uthor and James May},
    title = {Title B},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\cite{A}

\cite{B}

\cite{A,B}
\end{document}
```
With 2.8 beta gives
> Gauck et al., Title A
Gauck et al., Title B
Gauck et al., Title A; Gauck et al., Title B


While I would expect what I get from 2.7, namely
> Gauck et al., Title A
Gauck et al., Title B
Gauck et al., Title A, Title B

Since even though the name lists are different, we can't see that with out settings.

**Comment by plk** [comment] 2017-07-30 22:12
Ok, I think I see the fix now. We need to treat explicit "and others" as already having been manually truncated and so not to calculate special visibility for their name list. Can you try 2.8 again?

**Comment by moewew** [comment] 2017-07-31 06:29
Thank you, now everything works brilliantly.

Just a thought. In my tests it seemed that if `maxcitenames`/`mincitenames` and `maxbibnames`/`minbibnames` differ, for `namehash` the `...cite...` counters prevail. Can you confirm that is the case, or was it just by accident? If so, should we maybe change the part of the docs that I quoted above to make explicit that the `...cite...` counters are relevant.
Would it be possible to offer a `bibnamehash` that is truncated to `maxbibnames`/`minbibnames`? Currently the bibliography uses `fullhash`, but I could understand if people preferred a dash that followed the bib-truncated list (I can also understand the argument that `fullhash` should be used).

**Comment by plk** [comment] 2017-07-31 19:21
Good point. I've created `bibnamehash` and `<name>bibnamehash` which use `maxbibnames/minbibnames`. You are right that `namehash` and `<name>namehash` use `maxcitename/mincitenames`. I've updated the docs to reflect this. You'll need the latest dev of biblatex too as the bbl version has changed due to this.

**Comment by moewew** [comment] 2017-08-01 10:40
Brilliant. Thank you very much. Works as advertised.

**Closed** 2017-11-12 13:58 UTC
