### ISSUE TITLE
Biber 2.11 and authorname

### ISSUE THREAD

**Issue by hvoss49** [plk/biber#216] opened 2018-03-11 16:23 UTC
This worked in biber 2.10

```
@online{fontconfig,
  author ={{\texttt{freedesktop.org}}},
  sortname = {freedesktop},
  title = {Fontconfig},
  subtitle = {A library for configuring and customizing font access},
  date = {2016-06-15},
  urldate={2017-03-18},
  url = {https://www.freedesktop.org/wiki/Software/fontconfig/}
}
```

With biber 2.11 I'll get in the bbl file:

```      
     \name{author}{1}{}{%
        {{hash=44c5bd327e7f56833e134db2ab365efd}{%
           family={{\texttt{freedesktop.org}}},
           familyi={\texttt{freedesktop.org}}\bibinitperiod}}}%
      }
 ```
It is a wrong `familyi` entry, too many parentheses or a missing one before `\texttt` ... 

Is an authorname like `author={{foo}}` no more possible?

biber 2.11 and biblatex 3.11 (TL2018 pretest)

**Comment by plk** [comment] 2018-03-11 17:21
The problem is the utf8<->macro encoding which is required to get sorting right. There are always trade-offs in edge cases like this and it is caused by tweaking the conversion for other reported edge cases. It is impossible to have this 100% accurate. Such cases are really making formatting decisions in the data and so should be dealt with using the biber annotation feature really.

**Comment by moewew** [comment] 2018-03-11 17:50
See also https://github.com/plk/biblatex/issues/727, https://github.com/plk/biber/issues/215, https://github.com/plk/biber/issues/210.

`author = {{foo}}` should still work, its just constructs that start with a macro as in `author ={{\texttt{freedesktop.org}}},` and `author ={{\wikipedia}},`.

**Comment by hvoss49** [comment] 2018-03-11 19:22
Then a lot of bibliography data bases which uses for _years_  the notation with double braces
and following macro will fail. Not a  good idea ...

**Comment by plk** [comment] 2018-03-11 19:28
Double braces are ok, it's just arbitrary macros which are basically doing what styles should do.

**Comment by hvoss49** [comment] 2018-03-11 19:34
It has nothing to do with a style! It is the way how I have to write a single _part_  of  an "author".  And again: Why did the behaviour changes??

**Comment by plk** [comment] 2018-03-11 19:47
The changes are because I get many reports about the UTF8/macro conversion and accommodating some cases sometimes breaks others. Since this is a purely syntactical conversion--done purely to try to make sorting work for legacy .bibs which don't use UTF-8 or style-based presentation changes--it's impossible to make it work for every case. You can get what you need by using the data annotation feature of biber which was implemented to do exactly what you need - style changes for specific entries, including at the name part level.

You can also create and use a much more restricted UTF8/macro conversion table with biber, which would effectively stop conversion, try the `--decodecharset=null` option, which effectively turns of all conversion (at the expense of making sorting such entries impossible without explicit `sortname` fields etc.

**Comment by hvoss49** [comment] 2018-03-11 20:06
```
voss@shania:~/Links/texmf-local-latex/lucida-otf$ biber --decodecharset=null lucida-otf-doc
Unknown option: decodecharset
Usage:
      biber [options] file[.bcf]
      biber [options] --tool <datasource>
...
```

**Comment by sieversMartin** [comment] 2018-03-11 20:10
Am 11.03.2018 um 21:06 schrieb hvoss49:
> |voss@shania:~/Links/texmf-local-latex/lucida-otf$ biber
> --decodecharset=null lucida-otf-doc Unknown option: decodecharset Usage:
> biber [options] file[.bcf] biber [options] --tool <datasource> ... |

--decodecharsset
            ^^


-- 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by plk** [comment] 2018-03-11 20:11
Sorry, typo - it's `--decodecharsset=null`.

**Comment by hvoss49** [comment] 2018-03-11 20:19
doesn't work, the same problem as before ...

**Comment by u-fischer** [comment] 2018-03-13 21:20
I see the difficulties if arbitrary commands are used in sorting fields. But would it be possible to have *one*  working command? If e.g. one could use `\bibmarkup{texttt}{authorname}` and this would survive into the bbl one could define it to do whatever one wants.

**Comment by hvoss49** [comment] 2018-03-13 21:21
also doesn't work with a special recode file and an entry like 

```
<texmap>
  <decode_exclude>
    <char>texttt</char>
  </decode_exclude>
</texmap>
```

**Comment by moewew** [comment] 2018-03-14 10:14
Given the outcry this change has caused, maybe the least intrusive way would be to revert the fix for #210.

Since this is basically 'only' a bracing problem would it not be possible just to check if `familyi` has balanced braces and add missing braces at the end if need be? That way we at least don't break things so badly that compilation fails.

**Comment by hvoss49** [comment] 2018-03-14 10:37
yes, `familyi` is the only problem ...

**Comment by moewew** [comment] 2018-03-14 12:01
So far I came up with all the cases of the following MWE
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{elk,
  author   = {Elk, Anne},
  verba    = {Elk | E},
  title    = {All Plain},
  date     = {2012},
}
@book{belk,
  author   = {{Elk}, Anne},
  verba    = {*{Elk} | *{Elk}},
  title    = {Useless Family Braces},
  date     = {2013},
}
@book{alvarez,
  author   = {{\'A}lvarez, A.},
  verba    = {\'Alvarez | \'A},
  title    = {Diacritics},
  date     = {2014},
}
@book{balvarez,
  author   = {{{\'A}lvarez}, A.},
  verba    = {*{\'Alvarez} | *{\'Alvarez}/{{\'A}lvarez}},
  title    = {Diacritics},
  date     = {2014},
}
@book{nasa,
  author   = {{National Aeronautic and Space Administration}},
  verba    = {{National Aeronautic and Space Administration} | {National Aeronautic and Space Administration}},
  title    = {Diacritics},
  date     = {1972},
}
@book{wiki,
  author   = {{\wikipedia}},
  verba    = {{\wikipedia} | *{\wikipedia}},
  title    = {Parameterless Macro},
  date     = {2005},
}
@book{freedesktop,
  author   = {{\texttt{freedesktop}}},
  verba    = {{\texttt{freedesktop}} | *{\texttt{freedesktop}}},
  title    = {Macro with Parameter},
  date     = {2009},
}
@book{bracehack,
  author   = {{\relax El}k, Anne},
  verba    = {{\relax El}k | {\relax El}},
  title    = {Brace Hack},
  date     = {2010},
}
\end{filecontents}

\addbibresource{\jobname.bib}

\DeclareFieldFormat{verba}{\texttt{#1}}
\renewbibmacro*{addendum+pubstate}{\printfield{verba}}

\providecommand*{\wikipedia}{WikipediA}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

The `verba` field contains the expected value of `family` and `familyi` separated by `|` alternatives are given with `/`. If prefixed with a `*` the expected result is based on my guess or does not make much sense either way.

I'd welcome comments and corrections.

**Comment by moewew** [comment] 2018-03-15 12:17
@plk Is there a way to find out what the BibTeX parsing library does in the cases above before Biber applies its normalisation? Maybe we can find a better solution to the initials problem.

**Comment by plk** [comment] 2018-03-15 12:57
Yes, there is but it's a basic parser which is not trivial to change.

**Comment by moewew** [comment] 2018-03-15 12:59
So Biber has to do post-processing or it needs to re-implement the initials parsing (probably not desirable). If we take the basic parsing routine what is the raw output for my examples above? Is there any way for me to find out?

**Comment by plk** [comment] 2018-03-15 13:02
The issue is the macro->UTF8 conversion that happens before btparse generates the initials.

**Comment by moewew** [comment] 2018-03-15 13:12
Mhhh. OK.  

Maybe then the macro->UTF8 conversion needs to be less aggressive... (See also https://github.com/plk/biber/issues/219) But that is one of Biber's selling points, so ...

I just ran `--trace` on my example above, but I can't really put my finger on the problematic step.

The only things that look off are braces in intermediate steps such as
```
[330] Recode.pm:283> TRACE - String in latex_decode() before brace elimination now -> '{\textttfreedesktop}'
[330] Recode.pm:314> TRACE - String in latex_decode() now -> '{\texttt{freedesktop}}'
```
If I understand correctly brace matching is not something RegEx is particularly good at.

**Comment by plk** [comment] 2018-03-15 13:21
To do this properly, it needs a real parser to detect brace level, as btparse does. I did do this for a while years ago but it's very slow unless a binary module is found to do it. Regexps are really a pain in terms of brace levels etc. - it's just not really a purely syntactic problem which is why it's fragile.

**Comment by moewew** [comment] 2018-03-15 13:46
Mhhh. Is there no good way to do brace level detection in Perl? Maybe https://metacpan.org/pod/Text::Balanced or http://search.cpan.org/~abigail/Regexp-Common-2017060201/lib/Regexp/Common/balanced.pm can help (I have no idea, I just googled a bit).

I still don't quite understand where exactly things go wrong here. In some cases the `String in latex_decode() before brace elimination now` has unbalanced braces (brace surrogates), so that could be the actual problem.
```
String in latex_decode() before brace elimination now -> '{Álvarez, A.'
```
I don't understand why the first brace is not converted...

**Comment by hvoss49** [comment] 2018-03-15 18:42
From my point of view there should be a preprocessor which converts all TeX related stuff into the UTF characters. That can be done by a table, eg for ä and ı:

```
{\"{a}} => ä
{\"a} => ä
{\i} => ı

```
All other combinations for Ä and ı are wrong BibTeX syntax, eg 	`Universit\"at`, Id\i ot. Everything which is unknown will be unchanged, eg: `{{\wikipedia}}`. Then `biber` can 
read the bibliography and sort as usual and has only a problem when building initials.  

I prefer an empty initial if the long name starts with a backslash: 
\texttt{freedesktop} =>""
or as an alternative => "f"

the first character of the argument. 
Only some ideas ...

**Comment by plk** [comment] 2018-03-15 18:48
This is exactly what happens. The table is an XML file distributed with biber and is customisable by the user. The rules for doing these conversions are complex and interact in even more complex ways, hence the fragility. The problem is that braces and brace nesting really need to be handled semantically whereas regular expressions are purely syntactical. It also makes a difference at what scale one does these replacements. I recently moved from whole file to per-entry processing which solves some problems but any granularity smaller than this starts to have performance issues.

**Comment by hvoss49** [comment] 2018-03-15 19:38
That's fine! But then building `familyi` seems to be the only problem: And I cannot see why this should be related to the UTF8-conversion?  It seems to be simple (from my point of view) to test the first character of `family` if it is a letter??  Not?

**Comment by plk** [comment] 2018-03-21 20:58
This is fixed on the 2.12 DEV branch. It was nothing to do with the UTF8 decoding, it has to do with the pre-processing for initials generation. Some of this is customisable by the user (biber `noinit` option) but I added a general macro removal step.

**Closed** 2018-03-22 21:05 UTC

**Comment by moewew** [comment] 2018-03-23 09:27
That's very good news. Thank you very much.

Is there going to be a dev upload to Sourceforge we can play around with?

**Comment by plk** [comment] 2018-03-23 14:01
Just uploaded.

**Comment by moewew** [comment] 2018-03-23 14:40
Merci!

My example document from now compiles without errors. There is one quirk in the output, though. The entry `bracehack` with `author   = {{\relax El}k, Anne},` is converted to `family={{\relax\bibnamedelimb El}k},` this leads to an unwanted space. I know that the input is not really wellformed, but maybe there is something that can be done about this.

Following up on `{\relax Foo}` for https://github.com/plk/biber/issues/215 I noticed that while `author   = {{\relax El}k, Anne},` compiles, but gives unfortunate output, `author   = {Aardvark, {\relax Th}omas},` blows up with a SIGSEV. This seems rather odd to me. Is there a difference between the initials routine for given and family?

```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber, giveninits]{biblatex}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{thomas,
  author   = {Aardvark, {\relax Th}omas},
  title    = {Thommy},
  date     = {1900},
}

\end{filecontents}

\addbibresource{\jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```

**Comment by plk** [comment] 2018-03-23 14:51
There really is no way to account for all edge cases - we get perhaps one per year and I'd rather push UTF-8 as this solves just about all cases, as it should. It's only good luck that makes the first one work. There is no way to reliably do this because it would mean keeping state at every point (glyph) about whether we were in a brace group or not and what to do if we are. Perhaps if we had a binary module to do this it would be acceptable in performance terms but even then I'm not sure as this would have to interact with the regexp engine in complex ways.

**Comment by u-fischer** [comment] 2018-07-05 15:04
I just got a similar problem with `author={{\TeX{} User Group}}`. I hadn't yet the time to check if works again with the development version but I now wonder, why biber tries to create a familyi field for such entries with double braces. This are organization and an initial does make much sense imho. Or is it used somewhere?

**Comment by moewew** [comment] 2018-07-05 15:22
@u-fischer It works again with the current Biber 2.12 dev. I agree that it does not make a *lot* of sense to generate an initial from this, but in general I like it that Biber generates initials for all name parts and I guess it would add another layer of complexity to discern corporate authors from names beginning with legacy-ASCII-macros where you would want an initial. The meaning of braces is a bit too overloaded in BibTeX fields.
