### ISSUE TITLE
Use of uninitialized value $outtype in concatenation (.) or string at /tmp/par-6d726f7571756574/cache-73875c85d5252053a8a851d78c9322facb9c2224/inc/lib/Biber/Output/bbl.pm line 221

### ISSUE THREAD

**Issue by maieul** [plk/biber#302] opened 2020-01-07 13:54 UTC
Hi,

with biber 2.14 and biblatex 3.14, I get many line of "Use of uninitialized value $outtype in concatenation (.) or string at /tmp/par-6d726f7571756574/cache-73875c85d5252053a8a851d78c9322facb9c2224/inc/lib/Biber/Output/bbl.pm line 221"

Enclosed, you will find the .bib and .bcf

[biber.zip](https://github.com/plk/biber/files/4030920/biber.zip)

**Comment by plk** [comment] 2020-01-07 14:30
I believe this is already address in 2.15 dev version - I get no such lines with 2.15 and your test files.

**Comment by moewew** [comment] 2020-01-07 21:39
I can reproduce the issue with Biber 2.14, but the problem does not occur when I run the example with Biber 2.15.

@maieul Please note that it is *extremely* inconvenient to provide only a `.bcf` and `.bib` file for testing. Especially the fact that the `.bcf` cited every single entry from the `.bib` file explicitly was a pain: It made the `.bcf` file very large (about half a megabyte), so that Biber takes a long time to process it (@plk any chance for performance enhancements when reading the `.bcf`?) and it makes a binary search in the `.bib` file a pain because removing entries causes "entry not found warnings" that drown out the rest.

https://gist.github.com/moewew/3b0a1acdef6028e65059ef7c7e16f72c weighs only 300 kB because it uses `\nocite`. With that file we can reduce the `.bib` file to
```latex
@Bookininbook{BHG226_Lippomani1564t1,
  author        = {{Alexander Monachus}},
  title         = {Laudatio in apostolum Barnabam},
  crossref      = {Lippomani1564t1},
  date-added    = {2017-06-06 15:43:35 +0000},
  date-modified = {2017-06-06 15:45:14 +0000},
  pages         = {423-432 \mkbibparens{noté 423 par erreur}},
}

@Book{Lippomani1564t1,
  author        = {Loysius Lippomanus},
  title         = {Historiae de vitis sanctorum},
  date          = {1564},
  publisher     = {Martinus Verhaffelt},
  location      = {Louvain},
  volume        = {1},
}
```

My guess is that the problem has to do with case folding of new entry types from the data model (`@Bookininbook`).

It would be easier to properly investigate this with a LaTeX MWE (i.e. a TeX file and a `.dbx` file). Because then we can have a look at the human-readable form of the data model, not the more verbose XML version in the `.bcf`.

**Comment by maieul** [comment] 2020-01-08 09:23
@moewew ok, noted. But for me it was difficult to produce a MWE, as this
problem occurs with my full Phd thesis, and as I didn't get any
information about which entries cause the problem.

**Comment by moewew** [comment] 2020-01-08 17:15
@maieul Oh, I fully appreciate that it is quite some work to dig through 24000 lines of the `.bib`  file to identify a problematic entry and I know that you are well aware how important an MWE is to investigating problems like this.

The point I wanted to make is that a `.bcf` file is not only an unusual but in this case also very inconvenient way to provide an example. A short document along the lines of
```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\begin{filecontents}[force]{maieul.dbx}
% data model goes here
\end{filecontents}

\usepackage[style=authoryear, backend=biber, datamodel=maieul]{biblatex}

\addbibresource{biblio.bib}


\begin{document}
\nocite{*}
\end{document}
```
would have been much more convenient. And it is not much harder to provide such an MWE and verify that it reproduces the issue. I would even argue that it is harder to produce a `.bcf` that cites every single `.bib` entry explicitly than one from just `\nocite{*}` (at least if you do it manually).

Even if you don't know which entry is the problem, you can still try and find out with a binary search: Just remove half of the file and check if the issue persists. Of course in this case you may remove `crossref`s and you must hope that they are not involved and ignore the warnings caused by missing `crossref`s, but that is a risk I think one should take when trying to minimise the issue. In the worst case this procedure needs about 30 steps ($2 \log_2 24000$) compilation steps. But usually you are much quicker (if you are lucky you don't need the factor 2). That took me about 45 minutes last night. But it would have been quicker with a `.tex` document or a `.bcf` that didn't list every key explicitly.

---

I would still be interested in a TeX and `.dbx` file to investigate the issue further. You can use the `.bib` file I posted above.

**Comment by PHPirates** [comment] 2020-01-20 08:48
@moewew I believe the following reproduces the problem. Note that besides the error shown, the custom style is not used when I use `@exampletype`, but it _is_ used when I type `@unpublished` in the bibliography, which also makes the error disappear!

I think the update to biblatex 3.14 and biber 2.14 broke this, because in my real custom style it was printed correctly until I updated the packages. I did not yet try to revert to 3.13 to check with this MWE.

`main.tex`
```latex
\documentclass[11pt]{article}

\usepackage[bibstyle=biblatex-style-mwe]{biblatex}
\addbibresource{library.bib}

\begin{document}
  I did not cite~\cite{mylabel}.

  \printbibliography
\end{document}
```

`library.bib`
```bibtex
@exampletype{mylabel,
    author = {Name Surname and Name Surname},
    title = {This is not a title},
    examplefield = {MWE},
}
```

`biblatex-style-mwe.dbx`
```latex
\ProvidesFile{biblatex-style-mwe.dbx}[2020/01/20 v1.0 MWE for a custom biblatex style]

\DeclareDatamodelFields[type=field,datatype=literal]{examplefield}

\DeclareDatamodelEntryfields[unpublished]{examplefield}
\DeclareDatamodelConstraints[unpublished]{
  \constraint[type=mandatory]{\constraintfield{examplefield}}
}
```

`biblatex-style-mwe.bbx`
```latex
\ProvidesFile{biblatex-style-mwe}[2020/01/20 v1.0 MWE for a custom biblatex style]

\RequireBibliographyStyle{standard}
\RequireBibliographyStyle{numeric}

\DeclareBibliographyAlias{exampletype}{unpublished}

\DeclareBibliographyDriver{unpublished}{
  This is information about \printfield{title} by \printnames{author} as used in a \printfield{examplefield}
}
```

**Comment by moewew** [comment] 2020-01-20 19:06
@PHPirates Yes, that is definitely a related issue. The MWE works again with Biber 2.15, but I would argue that this usage was never really supported. If you use a new entry type that is not part of the default data model, you need to declare it first.

The correct code for the `.dbx` would at least contain
```
\DeclareDatamodelEntrytypes{exampletype}
```

If the type is correctly declared, the example works again even with Biber 2.14.
```latex
\documentclass[11pt]{article}

\begin{filecontents}{biblatex-style-mwe.bbx}
\ProvidesFile{biblatex-style-mwe.bbx}[2020/01/20 v1.0 MWE for a custom biblatex style]

\RequireBibliographyStyle{standard}
\RequireBibliographyStyle{numeric}

\DeclareBibliographyAlias{exampletype}{unpublished}

\DeclareBibliographyDriver{unpublished}{%
  This is information about \printfield{title} by \printnames{author} as used in a \printfield{examplefield}%
}
\end{filecontents}

\begin{filecontents}{biblatex-style-mwe.dbx}
\ProvidesFile{biblatex-style-mwe.dbx}[2020/01/20 v1.0 MWE for a custom biblatex style]

\DeclareDatamodelEntrytypes{exampletype}

\DeclareDatamodelFields[type=field,datatype=literal]{examplefield}

\DeclareDatamodelEntryfields[unpublished,exampletype]{examplefield}
\DeclareDatamodelConstraints[unpublished,exampletype]{
  \constraint[type=mandatory]{\constraintfield{examplefield}}
}
\end{filecontents}

\usepackage[bibstyle=biblatex-style-mwe]{biblatex}


\begin{filecontents}{\jobname.bib}
@exampletype{mylabel,
    author = {Name Surname and Name Surname},
    title = {This is not a title},
    examplefield = {MWE},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
  I did not cite~\cite{mylabel}.

  \printbibliography
\end{document}
```

**Comment by maieul** [comment] 2020-01-20 19:14
yes, of course. But in my case (Bookininbook), it concerns case folding, and, the historical entry types are case-insensitive. Why should it be for new entry type ?

**Comment by maieul** [comment] 2020-01-20 19:31
Here the real MWE

<code>
\documentclass[twoside,11pt]{book}
\usepackage[bibstyle=bookinother]{biblatex}

\begin{filecontents}[force]{biblio.bib}
@Bookininbook{BHG226_Lippomani1564t1,
  author        = {{Alexander Monachus}},
  title         = {Laudatio in apostolum Barnabam},
  crossref      = {Lippomani1564t1},
  date-added    = {2017-06-06 15:43:35 +0000},
  date-modified = {2017-06-06 15:45:14 +0000},
  pages         = {423-432 \mkbibparens{noté 423 par erreur}},
}

@Book{Lippomani1564t1,
  author        = {Loysius Lippomanus},
  title         = {Historiae de vitis sanctorum},
  date          = {1564},
  publisher     = {Martinus Verhaffelt},
  location      = {Louvain},
  volume        = {1},
}
\end{filecontents}
\addbibresource{biblio.bib}
\begin{document}

\nocite{*}
\printbibliography
\end{document}
</code>

(the datamodel bookinother is distributed with texlive).

With the current biber > not working
With past biber (I though 2 years ago) > it worked at this time
With 2.15 biber > it work.

It would be very useful to publish the fix for biber case folding...

**Comment by moewew** [comment] 2020-01-20 19:46
Thank you for the MWE.

As far as I can see the `.dbx` file does not properly declare `@bookininbook` as a new entry type. It should contain a line
```latex
\DeclareDatamodelEntrytypes{bookininbook}
```

I guess it should look like
```latex
%% Copyright 2016-… Maïeul Rouquette
%
% This work may be distributed and/or modified under the
% conditions of the LaTeX Project Public License, either version 1.3
% of this license or (at your option) any later version.
% The latest version of this license is in
%   http://www.latex-project.org/lppl.txt
% and version 1.3 or later is part of all distributions of LaTeX
% version 2005/12/01 or later.
%
% This work has the LPPL maintenance status `maintained'.
% 
% The Current Maintainer of this work is Maïeul Rouquette
% This work consists of the files realauthor.dbx, realauthor.bbx
\ProvidesFile{bookinother.dbx}
[2020/01/20 v2.3.2 biblatex bibliography style to have entry type for book edited in other entry type (MR)]

% 1. New entry types

\DeclareDatamodelEntrytypes{
  bookinarticle,
  inarticle,
  bookinthesis, bookinmathesis, bookinphdthesis,
  inthesis, inmathesis, inphdthesis,
  bookincollection, bookinproceedings, bookinreference,
  bookinincollection, bookininproceedings, bookininreference,
  inincollection, ininproceedings, ininreference,
  bookinjournal,
  ininbook, bookininbook,
  ininarticle, bookininarticle,
}

% 2. New fields

\DeclareDatamodelFields[type=list,datatype=name]{
  bookeditor,
  bookineditor,
  mainauthor,
}

% 3. For bookinother entrytypes
\DeclareDatamodelEntryfields[
  bookinarticle,
  inarticle,
  bookinthesis,bookinmathesis,bookinphdthesis,
  inthesis,inmathesis,inphdthesis,
  bookincollection,bookinproceedings,bookinreference,%
  bookinincollection,bookininproceedings,bookininreference,%
  inincollection,ininproceedings,ininreference%
  ]{%
  bookeditor,
  bookineditor
}

\DeclareDatamodelEntryfields[
  bookinarticle,
  inarticle,
  bookinincollection,bookininproceedings,bookininreference,%
  inincollection,ininproceedings,ininreference,%
  bookinjournal,%
  ininbook,bookininbook,%
  ]{%
  bookineditor
}
\DeclareDatamodelEntryfields[%
  ininarticle,bookininarticle%
  ]{%
  bookineditor,
  mainauthor,%
  }
% 4. For standard entry type
\DeclareDatamodelEntryfields[
  bookincollection,bookinproceedings,bookinreference
]{%
  bookeditor,
  bookineditor
}
% 5. Fields declared by morenames.dbx, for bookinother entrytypes
\DeclareDatamodelEntryfields[%
  bookincollection,bookinproceedings,bookinreference,%
  bookinincollection,bookininproceedings,bookininreference,%
  inincollection,ininproceedings,ininreference%
  ]{
  maineditor
}

\endinput
```

Frankly, I believe this is a bug in the `.dbx` file that should be fixed there. Admittedly, the bug in Biber may be annoying, but it is only showing that the data model is not complete.

**Comment by maieul** [comment] 2020-01-20 20:11
Ouch ! You are right ! In the past, biber was more tolerant, so I didn't see this problematic missing.

I will post on CTAN the correction. Thank you !

In any case, maybe we could have more explicit message in biber about the not declared entry type ?

**Comment by PHPirates** [comment] 2020-01-21 07:32
@moewew Thanks for the help! Indeed, I must have been confused by the error message to miss that I had to define the entry type, but it's fixed now.

**Closed** 2020-05-23 18:42 UTC
