### ISSUE TITLE
Biber for TeXLive on Alpine / MUSL libraries

### ISSUE THREAD

**Issue by krumeich** [plk/biber#255] opened 2019-02-24 12:35 UTC
First of all, thank you for developing and providing biber. 

I do have a small feature request: Could you provide a version for the x86_64-linuxmusl architecture? We use a customer specific TeX-Live installation in a Docker container. Alpine is the distro of choice, as it is small and lightweight. Unfortunately TeX-Live does not contain biber usable for this distro. All other binary packages (LuaTeX, xindy, etc) are compiled for the MUSL library format. 

The maintainer of TeX-Live says that biber binaries are provided by the upstream developer, I presume that would be you: https://github.com/TeX-Live/texlive-source/issues/10

Thanks!

**Comment by plk** [comment] 2019-02-25 09:20
I don't know much about the MUSL format - is this compatible with the usual linux distros?

**Comment by krumeich** [comment] 2019-02-25 10:26
Hi! 

MUSL is an alternative implementation of a standard library: https://www.musl-libc.org/. It promises several enhancements over libc. Unfortunately, it is not compatible with libc.

I should have mentioned in the opening post that I've developed a workaround for the problem: Compiling biber manually and using this self-compiled version in my Docker image. However, this is a lot of jumping through hoops because of dependencies to libraries and perl modules. 

In case you need a starting ground, I've created a docker image for compiling biber under Alpine. The source in on Github at https://github.com/krumeich/biber-alpine

The compiling part works well already. I'm not so sure about the packaging, though. Currently, I export the whole `/usr/local` tree with all the perl modules. Seems a bit much.

It'd be a lot more straightforward if TeX Live contained biber for the MUSL architecture.

Thanks for your attentention!

Alexander

**Comment by plk** [comment] 2019-02-28 21:29
I only want to add to my build farm for popular architectures as it's a lot of maintenance. However, if you'd like to support this architecture for TexLive, I can give you instructions and permissions on the biber Sourceforge repo which we use for releases. Basically, you would have to create the build scripts for the architecture following the existing ones, such as

https://github.com/plk/biber/blob/dev/dist/linux_x86_64/build.sh

It involves installing perl 5.26+ and all dependencies plus `PAR::Packer` which creates a stand-alone .exe. Then I would include this in the releases. When I make a release, I ask contributing builders to pull the git tag, build their .exe and upload to SF and then I do the release.

**Comment by krumeich** [comment] 2019-03-02 11:21
Good idea! Let's give it a try.

I changed my build setup to use PAR::packer and managed to build & package the dev branch (2.13 beta). However when I tried to build the master branch (2.12) in the same environment, "Build test" failed with 17/46 test programs. Have there been changes in the dependencies between 2.12 -> 2.13 beta that are not downward compatible?

One more question: the build.sh script requires OpenSSL 0.9.8. Alpine comes bundled with OpenSSL 1.1.1a. Is the older version a requirement?

I'll try to get more comfortable with the environment. Once I feel confident enough, I'll get back to you about the permissions/instructions. Please bear in mind that I don't have any experience using oder developing with perl.

**Comment by plk** [comment] 2019-03-02 15:20
Those build scripts are just examples - I use relatively old libs in some cases just because that’s what the perl modules on my build machines were compiled against. You can use whatever you want since Par::Packer bundles all of these things into the packed .exe and as long as that .exe works on a system with no perl at all, it’s all fine.

There were quite some changes from 2.12 but they shouldn’t make the tests fail - I can have a look at the failures if you send a log. Generally, if you do a “Build installdeps”, the tests should pass.

What I do with the build.sh script is ask builders to check this in to a suitably names subdir under dist/ and then I can update it with any module dependency changes etc. so that everything is in sync.

If you give me your github/Sourceforge Ids, I’ll add you as a contributor.

**Comment by krumeich** [comment] 2019-03-02 20:40
Thanks for the clarification re: library versions. With today's experiments I'd figured as much.

I've now got a Docker container that builds and packages biber under Alpine Linux:
https://github.com/krumeich/biber-alpine

For testing purposes, another container runs "biber --version" in an empty Alpine, with only biber and no perl installed. The assumption is that if the executable doesn't crash it is compatible with the platform: 
https://github.com/krumeich/biber-alpine-test

As for the problems with 2.12: It'd be great if you could take a look at the log file attached to this message. Unfortunately you can't see the commands as they are not printed to stdout. Shouldn't be too difficult though.

For GitHub and SourceForge IDs, my username is "krumeich".

[biber-alpine-master.log](https://github.com/plk/biber/files/2922475/biber-alpine-master.log)

**Comment by plk** [comment] 2019-03-02 21:21
I’ve added you on SF and github. Running “biber —version” is usually fine. I would also get the generic .bcf from SF and try:

biber —validate_control —convertcontrol test.bcf

As this will test whether the XML/XSLT  libs are installed correctly. You should get validation messages (which succeed) and a .html file output which is a representation of the .bcf.

Hmm, that log isn’t too useful - you can run biber on each of the .t files for more details. The test files were changed a lot from 2.12. to 2.13 and so you have to run the right version of biber on them due to internals changes.

PK

> On 2 Mar 2019, at 9:40 pm, Alexander Krumeich <notifications@github.com> wrote:
> 
> Thanks for the clarification re: library versions. With today's experiments I'd figured as much.
> 
> I've now got a Docker container that builds and packages biber under Alpine Linux:
> https://github.com/krumeich/biber-alpine
> 
> For testing purposes, another container runs "biber --version" in an empty Alpine, with only biber and no perl installed. The assumption is that if the executable doesn't crash it is compatible with the platform:
> https://github.com/krumeich/biber-alpine-test
> 
> As for the problems with 2.12: It'd be great if you could take a look at the log file attached to this message. Unfortunately you can't see the commands as they are not printed to stdout. Shouldn't be too difficult though.
> 
> For GitHub and SourceForge IDs, my username is "krumeich".
> 
> biber-alpine-master.log
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Dr Philip Kime

**Comment by moewew** [comment] 2019-03-03 05:29
Sorry to barge in, but couldn't the build failures have to do with <https://github.com/plk/biber/commit/6b34ad6ee003d5bacb91f0cd1540ec9a74f1a7b0> and in particular <https://github.com/plk/biber/commit/6b61b4c13778cf638f82569ab9e413f09f111ba5>? If Biber 2.12 is also built with the newer U::C version that Biber 2.13 requires that could explain the diff.

**Comment by plk** [comment] 2019-03-03 09:55
Ah yes, that's certainly a possibility - I had forgotten the U::C change. That would explain it as this makes most hashes in the `.bbl` test change so I suspect you can ignore these errors.

**Comment by krumeich** [comment] 2019-03-03 17:54
Thanks, @moewew  for the explanation. 

@plk I've created a pull request for the musl-based build script.

If it's alright for you, my first contribution would be to the 2.13 version. I think I'm settled so far that we can close this issue.

**Comment by plk** [comment] 2019-03-03 23:42
Thanks, merged. can you send me your email address so I can add you to the biber builders list. I send out an email to the builders to update their SF build dirs just before a release.

**Comment by krumeich** [comment] 2019-03-05 22:09
Sure. Please add alexander@krumeich.de to the list.

**Comment by norbusan** [comment] 2019-03-07 10:58
Thanks everyone from the TeX Live team for the nice cooperation and great work!

**Comment by svenevs** [comment] 2019-03-08 06:32
Hello, thank you **very much** for working on this.  I apologize if this question does not belong here, I'm not well versed in all of the moving parts.

I tried downloading the prototype binary hosted with `wget https://github.com/krumeich/biber-alpine-test/raw/master/biber-linux_x86_64-musl`, which is successful insofar as `biber --version` works (woot!  I couldn't get that to happen...).  But when using it with `biblatex`:

```
INFO - This is Biber 2.13 (beta)
...
ERROR - Error: Found biblatex control file version 3.5, expected version 3.6.
This means that your biber (2.13) and biblatex (3.12) versions are incompatible.
```

I tried `install-tl` with 2018 (current, frozen) version, as well as pretest version, but I think I'm misunderstanding the requirements for either the binary or biblatex (first line says "had 3.5, need 3.6" but then second line says "have 3.12"?).  I am still trying to learn how to build this from source, but wasn't sure if this is a problem with my setup or the packaged binary.  If the latter, it would be good to fix before it hits SourceForge (I'm happy to help do any testing!).

Sorry again if the answer to this is obvious...I'm a novice with building both perl and tex :/

**Comment by moewew** [comment] 2019-03-08 08:24
`biblatex` and Biber are developed together and have tightly-nit dependencies. Biber 2.13 (dev) only works together properly with `biblatex` 3.13 (dev). You got the new (dev) Biber binary, but do not have the dev version of `biblatex` that matches it (https://sourceforge.net/projects/biblatex/files/development/). (Your `biblatex` is still the current release version 3.12.)

The version numbers in the first line refer to the internal *biblatex control file* (`.bcf`) version, whose versioning need not coincide with the actual `biblatex`/Biber version number. The human-readable version identifiers are in the second line: You have Biber 2.13, but `biblatex` 3.12. (Matching would be Biber 2.12/`biblatex` 2.12 or Biber 2.13/`biblatex` 3.13).

**Comment by svenevs** [comment] 2019-03-08 10:57
Ah, this makes a lot more sense now, thank you for explaining what the different version numbers @moewew.  I can confirm that with a 3.13 (dev) installed, the binary produced by @krumeich for an alpine linux image works.  Awesome!!!

For the future timeline, will it look something like this?

1. At some point the musl binary will be [added to SourceForge](https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/Linux/).
2. After TEX 2019 rolls out ~April 30, the `tlmgr install biber biblatex` will have access for `x86_64-linuxmusl` targets? (Or `install-tl` if doing a `scheme=full`, the point being the musl binaries will be available).  Not necessarily at the time that 2019 rolls out, but whenever biblatex 3.13 // biber 3.12 are officially released, then users can install them through CTAN since the package lists won't be frozen.

Thanks again to all parties involved here (as well as for biber!) This is a huge time saver for docker / alpine users :slightly_smiling_face:

**Comment by plk** [comment] 2019-03-08 20:27
Excellent work @krumeich - please feel free to add a top-level dir (on same level as Linux, Windows etc.) on SF in the development folder and upload development versions whenever you like. I control the  standard linux, windows and OSX build servers and so I always upload dev versions of these during development cycles but if you track the git dev branch, you will see any changes and can build/upload whenever you wish in development cycles. I will coordinate releases with everyone.

**Comment by krumeich** [comment] 2019-03-09 11:20
@plk Thanks for the kind words, really appreciate it. Could you check my permissions on SF? Unfortunately I don't see the options to add files or folders on SourceForge.

Having tested against the generic test files, there were some libraries still missing. This is now fixed in the 2.12 binary that you can grab from https://krumeich.de/biber-linux_x86_64-musl_2.12.tar.gz

The 2.13(beta) binary is ready for testing. I ran into the same version incompatibilities as @svenevs. Do you have generic test files that are compatible with 2.13(beta)?

**Comment by plk** [comment] 2019-03-09 11:31
I have updated the SF perms - let me know when you have created the folders and files you need as then normal developer rights are find to update the files.
I have added a "test-dev.bcf" to the "testfiles" folder on SF which uses the same .bib but has the right versions for testing with DEV biblatex.

**Comment by krumeich** [comment] 2019-03-09 11:43
OK, done! The 2.13(beta) binary verifies against `test-dev.bcf` and is up on SourceForge in the new [Linux-musl folder](https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/development/binaries/Linux-musl/). Give it a try!

**Comment by svenevs** [comment] 2019-03-11 18:32
It works beautifully, thanks again!  For the archives if there are users confused about how to do this, you have two options:

## Option 1

Use the newly hosted musl binaries from sourceforge.  You need to

1. Download the binary from sourceforge
2. Download / install development version of biblatex.

[A sample of how to do this is in production here](https://github.com/pandoc/dockerfiles/blob/5dcadbcc30ceac61d51c093ee60f6e8072fa5515/alpine/latex/Dockerfile#L34-L80).  The only thing of note there is that chaining everything under one `RUN` command will save you ~60 MB, so don't separate that out into multiple `RUN` statements.

## Option 2

You can build it from source yourself, the procedure is [hosted by @krumeich here](https://github.com/krumeich/biber-alpine).  You would be well served to use a [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) using this approach.

**Closed** 2019-03-16 16:50 UTC
