### ISSUE TITLE
Converting date field into year and month field fails with biber 2.15

### ISSUE THREAD

**Issue by LukasCBossert** [plk/biber#339] opened 2020-10-05 19:30 UTC
There is a question on TeX.SE about this issue https://tex.stackexchange.com/questions/265895/biblatex-how-to-convert-date-field-into-year-and-month-field/.

In the answer von @moewew he shows a solution (https://tex.stackexchange.com/a/265979/98739) for biber 2.15 but it seems not to work (anymore).

For the sake of completeness I paste the solution code below (credits go to @moewew).

------------

We need the following config file, called, say, `biber-date.conf`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config>
  <output_fieldcase>lower</output_fieldcase>
  <datamodel>
    <fields>
      <field fieldtype="field" datatype="literal">year</field>
      <field fieldtype="field" datatype="literal">month</field>
    </fields>
    <entryfields>
      <field>year</field>
      <field>month</field>
    </entryfields>
  </datamodel>
  <sourcemap>
    <maps datatype="bibtex">
      <map map_overwrite="1">
        <map_step map_field_source="date" map_match="[0-9]{4}-([0-9]{2})" map_final="1"/>
        <map_step map_field_set="montha" map_field_value="$1"/>
      </map>
      <map map_overwrite="1">
        <map_step map_field_source="date" map_match="([0-9]{4})" map_final="1"/>
        <map_step map_field_set="yeara" map_field_value="$1"/>
      </map>
    </maps>
  </sourcemap>
</config>
```

To convert the `date` fields in your `.bib` file run

    biber --tool --configfile=biber-date.conf <yourbibfile>

For the example file `augustus.bib`

    @article{kattan_timeseries_2015,
      title = {Time-series event-based prediction: An unsupervised learning framework based on genetic programming},  
      journaltitle = {Information Sciences},
      author = {Kattan, Ahmed and Fatima, Shaheen and Arif, Muhammad},
      date = {2015-04}
    }
    @book{lorem,
      title = {Lorem},  
      author = {Anne Uthor},
      date = {2015}
    }
    @book{ipsum,
      title = {Ipsum},  
      author = {Anne Uthor},
      date = {2015-08-07},
    }

the output (which you can find in `augustus_bibertools.bib` after the `biber --tool --configfile=biber-date.conf augustus.bib` run) is

    @article{kattan_timeseries_2015,
      author = {Kattan, Ahmed and Fatima, Shaheen and Arif, Muhammad},
      journaltitle = {Information Sciences},
      month = {4},
      title = {Time-series event-based prediction: An unsupervised learning framework based on genetic programming},
      year = {2015},
    }
    
    @book{lorem,
      author = {Uthor, Anne},
      title = {Lorem},
      year = {2015},
    }
    
    @book{ipsum,
      author = {Uthor, Anne},
      date = {2015-08-07},
      title = {Ipsum},
    }

**Comment by bersbersbers** [comment] 2020-10-12 15:18
This may be a duplicate of #162. See #322 for a potentially interesting workaround (`--output-legacy-date`).

**Comment by HaoZeke** [comment] 2021-05-25 13:57
As of `2.16` I can use:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Got the date from https://gist.githubusercontent.com/mkouhia/f00fea7fc8d4effd9dfd/raw/500e9dbc6aa43a47e39c45ba230738ff4544709f/biblatex-to-bibtex.conf -->
<config>
  <output_fieldcase>lower</output_fieldcase>
  <output_resolve>1</output_resolve>
  <output_safechars>1</output_safechars>
  <output_format>bibtex</output_format>
  <sourcemap>
    <maps datatype="bibtex">
      <!-- Easy type conversions -->
      <map>
        <map_step map_type_source="report" map_type_target="techreport"/>
        <map_step map_type_source="online" map_type_target="misc"/>
      </map>
      <!-- Date to year, month -->
      <map>
        <map_step map_field_source="date"
        map_field_target="year" />
      </map>
      <map>
        <map_step map_field_source="year"
        map_match="(\d{4}|\d{2})-(\d{1,2})-(\d{1,2})"
        map_final="1" />
        <map_step map_field_source="year"
        map_match="(\d{4}|\d{2})-(\d{1,2})-(\d{1,2})"
        map_replace="$1" />
        <map_step map_field_set="month" map_origfieldval="1" />
        <map_step map_field_source="month"
        map_match="(\d{4}|\d{2})-(\d{1,2})-(\d{1,2})"
        map_replace="$2" />
      </map>
      <map>
        <map_step map_field_source="year"
        map_match="(\d{4}|\d{2})-(\d{1,2})" map_final="1" />
        <map_step map_field_source="year"
        map_match="(\d{4}|\d{2})-(\d{1,2})" map_replace="$1" />
        <map_step map_field_set="month" map_origfieldval="1" />
        <map_step map_field_source="month"
        map_match="(\d{4}|\d{2})-(\d{1,2})" map_replace="$2" />
      </map>
    </maps>
  </sourcemap>
</config>
```

With `biber --tool --configfile=biberConf.xml references.bib --output-file refsTmp.bib --output-legacy-date --output-field-replace=location:address,journaltitle:journal`

[Detailed here](biber --tool --configfile=biberConf.xml references.bib --output-file refsTmp.bib --output-legacy-date --output-field-replace=location:address,journaltitle:journal).

**Closed** 2022-06-20 10:22 UTC
