### ISSUE TITLE
Problems with $\| $ -- no output 

### ISSUE THREAD

**Issue by marvinmarvin** [plk/biber#88] opened 2015-11-02 19:17 UTC
The enclosed (almost) minimal example gives no pages of output on  a recent texlive 2015 (biber version 2.2) with 
latex allbib; biber; latex allbib

After removing the Abstract in the bibentry output is as expected.

allbib.tex:

\begin{filecontents*}{testbib.bib}
% This file was created with JabRef 2.10.
% Encoding: UTF8

@Article{GPS96,
  Title                    = {Any Nonincreasing Convergence Curve is Possible for {GM}RES},
  Author                   = {Anne Greenbaum and Vlastimil Pták and Zdenuek Strakous},
  Journal                  = {SIAM J.\ Matrix Anal.\ Appl.},
  Pages                    = {465--469},
  Volume                   = {17},
  Year                     = {1996},
  Language                 = {english},
  Number                   = {3},

  Abstract                 = {$\| r^0 \| = f(0)$},
}
\end{filecontents*}

\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage{selinput}
\SelectInputMappings{
  adieresis={ä},
  germandbls={ß},
  Euro={€},
}

\usepackage[%
backend=biber%
]{biblatex}
\addbibresource{testbib.bib} 

\begin{document}

\nocite{*}

\printbibliography

\end{document}

**Comment by plk** [comment] 2015-11-02 20:11
You probably want to use a sourcemap to remove abstracts like that before biblatex sees them. This is a common question on tex.stackexchange.com.

**Comment by marvinmarvin** [comment] 2015-11-03 07:15
No, I want that abstracts like 

  Abstract                 = {Given a nonincreasing positive sequence $f(0) \geq f(1) \geq \cdots \geq f(n-1) > 0$, it is shown that there exists an $n$ by $n$ matrix $A$ and a vector $r^0$ with $\| r^0 \| = f(0)$ such that $f(k) = \| r^k \|$, $k=1, \ldots , n-1$, where $r^k$ is the residual at step $k$ of the GMRES algorithm applied to the linear system $Ax=b$, with initial residual $r^0 = b - A x^0$. Moreover, the matrix $A$ can be chosen to have any desired eigenvalues.},

are displayed correctly (with biblatex-option style=reading) -- as biber 1.9 does. 
I only wanted to submit a small example.
So, the problem is that biber 2.2 does not process this file correctly.

**Comment by plk** [comment] 2015-11-03 11:40
Ah, ok, thanks, I'll look into it.

**Comment by plk** [comment] 2015-11-03 11:55
Hmm, It works fine for me - try this MWE which uses your Abstract above:

```
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@article{A01,
  author = {John Smith},
  year = {2001},
  title = {Title},
  Abstract = {Given a nonincreasing positive sequence $f(0) \geq f(1) \geq \cdots \geq f(n-1) > 0$, it is shown that there exists an $n$ by $n$ matrix $A$ and a vector $r^0$ with $| r^0 | = f(0)$ such that $f(k) = | r^k |$, $k=1, \ldots , n-1$, where $r^k$ is the residual at step $k$ of the GMRES algorithm applied to the linear system $Ax=b$, with initial residual $r^0 = b - A x^0$. Moreover, the matrix $A$ can be chosen to have any desired eigenvalues.}
}
\end{filecontents}

\usepackage[backend=biber,style=reading]{biblatex}

\addbibresource{\jobname.bib}

\begin{document}
Some text \autocite{A01}.
\printbibliography
\end{document}
```

**Comment by plk** [comment] 2015-11-03 11:57
You might want to post to TSE - it might be to do with the other things in your example above. It works for me with lualatex and pdflatex+inputenc.

**Comment by marvinmarvin** [comment] 2015-11-03 15:52
I am very sorry, but I just now recognized that Markdown or whoever converts "\\|" to "|" -- I have to use \\ twice. So the critical abstract-line looks as following:

Abstract                 = {Given a nonincreasing positive sequence $f(0) \geq f(1) \geq \cdots \geq f(n-1) > 0$, it is shown that there exists an $n$ by $n$ matrix $A$ and a vector $r^0$ with $\\| r^0 \\| = f(0)$ such that $f(k) = \\| r^k \\|$, $k=1, \ldots , n-1$, where $r^k$ is the residual at step $k$ of the GMRES algorithm applied to the linear system $Ax=b$, with initial residual $r^0 = b - A x^0$. Moreover, the matrix $A$ can be chosen to have any desired eigenvalues.}

(Yes, I now checked in the preview)

I believe the essential point is \\| in the abstract or wherever, therefore my original abstract-line was 

  Abstract                 = {$\\| r^0 \\| = f(0)$}

which fails on  biber 2.2, but works fine on biber 1.9.

**Comment by plk** [comment] 2015-11-03 16:08
Ah, ok, I am looking into it.

**Comment by plk** [comment] 2015-11-03 16:27
Please try biber 2.3 from the development folder on sourceforge. You will also need the development version (3.2) of biblatex. This should be fixed now - it was due to a regression in the fairly major rewrite of the latex <-> utf8 interface in version 2.0 I think.

**Closed** 2015-12-05 14:39 UTC
