### ISSUE TITLE
compliling with biber2.8 results in "Can't decode ill-formed UTF-8 octet sequence <E4> ..."

### ISSUE THREAD

**Issue by m-vogel** [plk/biber#191] opened 2017-11-15 21:06 UTC
A document working with biber 2.7 doesn't compile after updating to biblatex 3.8 and biber 2.8 (via TeXLive) any more. The resulting error is:  Can't decode ill-formed UTF-8 octet sequence <E4> at C:\Users\NAME\AppData\Local\Temp\par-4d6f\cache-4b419f4e7b1e3e9cdb78a8c

The biber logfile has:
[0] Config.pm:302> INFO - This is Biber 2.8
[0] Config.pm:305> INFO - Logfile is 'GuP2.blg'
[36] biber-MSWIN32:313> INFO - === 

My style-files are changed with respect to the incompatible changes of biblatex, but the error shows up also with authoyear. So I have no idea.

The document loads biblatex with
\usepackage[backend=biber,
style=stw,              % changing this is no remedy 
bibencoding=utf8, % changing this is no remedy 
indexing=cite,%      %  changing this is no remedy 
language=german]{biblatex}

Many thanks in advance,
best, 
Matthias

**Comment by plk** [comment] 2017-11-16 09:05
Hmm, can you give me a minimal example?

**Comment by m-vogel** [comment] 2017-11-16 16:42
First, here is the complete error message:

Can't decode ill-formed UTF-8 octet sequence <E4> at C:\Users\NAME\AppData\Local\Temp\par-4d6f\cache-4b419f4e7b1e3e9cdb78a8c63410aec04e2636e8\inc\lib/File/Slurper.pm line 63.

After extensive testing I isolated the culprit. It is a package of mine that uses \map. It worked with biber 2.7 but it does not with 2.8. Here is a shortened example from the code:

\DeclareSourcemap{
    \maps[datatype=bibtex]{
       \map{
           \step[fieldsource=publisher, match=\regexp{(The\sMIT\sPress)|(MIT\sPress)}, replace={MIT}]
           \step[fieldsource=journaltitle, match={Phänomenologische Forschungen}, replace=\regexp{Phänomenol.\x20Forsch.}]
           \step[fieldsource=location, match=\regexp{(Frankfurt\sam\sMain)|(Frankfurt/Main)}, replace={Frankfurt/M.}]
          }
      }
    }

I suspect there’s something is wrong with \s and \x20… Perhaps this is just a bad hack of mine that worked with 2.7 but came to the surface by the update. 

Best,
Matthias

**Comment by plk** [comment] 2017-11-16 18:57
I think this is a bug and I am looking into it.

**Comment by plk** [comment] 2017-11-17 11:00
Can you try biber 2.9 in the development folder on Sourceforge? No need to upgrade biblatex.

**Comment by m-vogel** [comment] 2017-11-17 12:35
Compiling with the new 2.9 (beta) results in the same error. After systematically commenting out \step-lines within \map{} I found the following line to be the cause of the error.

\step[fieldsource=journaltitle, match={Phänomenol. Forsch.}, replace=\regexp{Phänomenologische\x20Forschungen}]

This is the only step (within the macro) in which both "match" and "replace" contain Umlauts and "replace" is defined in terms of regexp.

**Comment by plk** [comment] 2017-11-17 12:42
Hmm, can you give me a complete MWE here? I also thought that this step was the issue and used it as a test but I couldn't reproduce.

**Comment by m-vogel** [comment] 2017-11-17 13:31
Here is a MWE:
[MWE-bibverbosity.txt](https://github.com/plk/biber/files/1482417/MWE-bibverbosity.txt)

**Comment by plk** [comment] 2017-11-18 21:24
This is a very interesting bug you have found. You are doing nothing wrong. Looking into it. The error comes when `biber` reads in the `.bcf` control file to check it is well-formed. It seems that the ctrl-file in your case (due to inputenc) is not written in utf-8, which is rather bad for XML ...

**Comment by plk** [comment] 2017-11-18 21:53
This is fixed in `biber` 2.9 which will be released shortly. I would generally recommend switching to a fully UTF-8 compliant tex engine to avoid such issues and to get the best out of biber but biber will now try to read the control file as latin1 (which it shouldn't be really) and will automatically convert it to UTF-8 if necessary.

**Closed by plk** 2017-11-18 21:53 UTC

**Comment by m-vogel** [comment] 2017-11-19 12:48
Many thanks! What would be a fully UTF-8 compliant tex engine? (luatex?) I’m using pdftex and all my source files are coded in UTF-8…

**Comment by plk** [comment] 2017-11-19 13:39
Yes - you can ask about switching on tex.stackexchange.com - there will be a lot of help there. Luatex or xetex are fully utf8 compliant engines. I personally only use luatex for everything. Then you don't use `fontenc` or `intputenc` packages, just the `fontspec` package and your document and .bib can be pure utf8.

**Comment by aking7** [comment] 2018-01-03 11:48
I am having the same issue in biber 2.10.

**Comment by plk** [comment] 2018-01-04 16:10
Can you give a MWE?

**Comment by moewew** [comment] 2018-01-04 20:08
@aking7 Please make sure that it is not one of the problems mentioned in https://tex.stackexchange.com/q/402714/35864. Biber is a bit stricter about non-ASCII chars if it is run in ASCII mode.

An [MWE](https://tex.meta.stackexchange.com/q/228/35864)/[MWEB](https://tex.meta.stackexchange.com/q/4407/35864) is needed. Since this is about file encodings, you should check them and report them here as well. It is also important to know how (with which engine) you compile your document.

**Comment by aking7** [comment] 2018-01-05 09:34
Thanks @moewew. It was an error with one of my .bib files that somehow was working with the older versions of biber.

**Comment by DrZooDinghy** [comment] 2018-02-17 15:02
Any suggestions what to do?
I use: \usepackage[utf8]{inputenc}  and bibencoding=utf8 but still get the message:

INFO - This is Biber 2.10
INFO - Logfile is 'main.blg'
INFO - Reading 'main.bcf'
INFO - Found 448 citekeys in bib section 0
INFO - Processing section 0
INFO - Looking for bibtex format file './TeX_files/bibliography utf8.bib' for section 0
ERROR - Data file './TeX_files/bibliography utf8.bib' cannot be read in encoding 'UTF-8': Can't decode ill-formed UTF-8 octet sequence <EB> at C:\Users\Mikayy\AppData\Local\Temp\par-4d69634b7265\cache-0551d9210c1a0ac577200d0bf452c95f606ff4a1\inc\lib/File/Slurper.pm line 63.

INFO - ERRORS: 1

**Comment by DrZooDinghy** [comment] 2018-02-18 09:48
Interestingly, I found that I had created a second version of the bib file that I called bibliography-utf8.bib a year ago. I can't remember what I did change in this version, but it allowed me to compile the bibliography. I now imported the older version bibliography.bib that didn't work back then. Now, however, I can compile it without problems.
