### ISSUE TITLE
Running biber from within a script

### ISSUE THREAD

**Issue by hvoss49** [plk/biber#448] opened 2023-04-11 18:56 UTC
To create a lot of examples I run tons of files via several scripts. With one of the last updates of biber/biblatex I have a problem with biber on macOS/Ventura (TL2023) running the scripts with bash:

```
...
### pdflatex 04-02-25.ltx2 (1)
### run command (biber 04-02-25)
error: /Library/Developer/CommandLineTools/usr/bin/lipo: can't move temporary file: /var/folders/ww/7jbdn2090q1bdng_1mplhtqr0000gn/T/par-766f7373/cache-4edecc3c88fd313ee8c9289f29dfd8b198e3e70a/thin/biber to file: /var/folders/ww/7jbdn2090q1bdng_1mplhtqr0000gn/T/par-766f7373/cache-4edecc3c88fd313ee8c9289f29dfd8b198e3e70a/thin/biber.lipo (No such file or directory)
biber: extracting x86_64 binary with lipo failed (wstatus=256)
######################################################################
### E R R O R                                                      ###
######################################################################
```

In the directory `.../thin/`  there is only a file `biber` and not `biber.lipo`

Running an example in a terminal is no problem ...

**Comment by krumeich** [comment] 2023-04-11 19:16
Herbert, that is a problem that's recently come up for a few people who use biber concurrently. The problem is that biber self-extracts to a temp directory and macOS's `lipo` utility separates the binary for the specific architecture from the universal binary. Two processes performing this simultaneously cause the error when `lipo` cannot write the extracted binary to a file.  One can easily reproduce this problem by running `biber --help | biber --help`. Unfortunately, there is no perfect solution. 

I've devised a workaround for my project: I set a specific variable `PAR_GLOBAL_TEMP` on every run of biber. So every one of my ~20 documents gets its own expanded instance of biber and thus its own copy of the universal binary so that `lipo`can exclusively on a single binary. This is feasible in my case since my project consists of ~20 documents and not an arbitrary number. They are processed with `latexmk`. Each run of `latexmk` is prepended with a variable declaration `PAR_GLOBAL_TEMP=/tmp/bibercache/<doc_specific_dirname>`. Of course this is semi-automated in a Makefile, no need to type this everytime.

The price for this is paid in storage space: Each expanded instance of biber takes up ~300 MB, so I waste approximately 6 GB of SSD space on biber caches. Not an ideal solution, but workable to a certain extent.

If you're interested, I can provide further details on the workaround.

**Comment by krumeich** [comment] 2023-04-11 20:29
This sounds good. I suppose one would have to do this only when a new version of biber is installed. Since this is not too often, it could be a viable workaround for users who want to use concurrent instances of biber.

**Comment by hvoss49** [comment] 2023-04-12 14:08
What happens if you delete biber´s  temp folder (in my case: `/var/folders/ww/7jbdn2090q1bdng_1mplhtqr0000gn/T/par-766f7373`,  and then run the _extracted_ biber, saved in the default TeX binary dir?

in my case it creates a new directory with all files and all is fine. Maybe that I do not see the important point ...

**Comment by plk** [comment] 2023-04-12 14:19
Normally, there is one temp cache folder which `biber` unpacks itself to on first run of a binary with a hash different from any previous `biber`. However, if you run the universal binary, it first unpacks itself, runs `lipo` to extract the correct thin binary and then runs the thin binary which, as it has a different hash than the (larger) universal binary, will unpack itself again in a different place which will persist over all runs of the same thin binary. You can delete the cache from the universal binary with no impact if you are using the thin binary directly.

By the way, if you just want to simplify things, you can extract the thin binary from the universal without running it. You can see the thin binary architectures in the universal binary like this:

```
lipo -info /usr/local/texlive/2023/bin/universal-darwin/biber
Architectures in the fat file: /usr/local/texlive/2023/bin/universal-darwin/biber are: x86_64 arm64 
```

and you can extract the thin binary you want like this (say you want to xx6_64 Intel thin binary):

```
lipo -extract_family x86_64 -output <some_path_to_thin_biber> /usr/local/texlive/2023/bin/universal-darwin/biber
```

This way there will be no separate cache for the universal binary and the thin binary will just work as expected.

**Comment by hvoss49** [comment] 2023-04-12 14:29
I used the already unpacked  version:

```
iMac:~ voss$ lipo -info /usr/local/texlive/current/bin/universal-darwin/biber
Non-fat file: /usr/local/texlive/current/bin/universal-darwin/biber is architecture: x86_64

```

and in my texlive/bin:

```
iMac:~ voss$ ls -la /usr/local/texlive/current/bin/universal-darwin/biber*
-rwxr-xr-x  1 voss  staff   40263952 11 Apr 21:05 /usr/local/texlive/current/bin/universal-darwin/biber
-rwxr-xr-x  1 voss  staff  101082976  8 Mär 13:59 /usr/local/texlive/current/bin/universal-darwin/biber-ms
-rwxr-xr-x  1 voss  staff  101075728  6 Mär 23:29 /usr/local/texlive/current/bin/universal-darwin/biber.packed
-rwxr-xr-x  1 voss  staff   40263952 11 Apr 21:05 /usr/local/texlive/current/bin/universal-darwin/biber.unpacked

```

**Comment by hvoss49** [comment] 2023-04-12 14:50
Yes, all is fine ... more or less :-)
I'll ask Norbert if there exists a "postaction" option for TL packages which can do the lipo run.

Maybe you already did this ..

**Comment by plk** [comment] 2023-04-12 14:54
Can also just provide seperate x86_64 and arm64 binaries but I was explicitly asked to combine into a universal for simplicity ...

**Comment by hvoss49** [comment] 2023-04-12 18:24
It is possible to create a short file `biber.pl` in the directory `/usr/local/texlive/2023/tlpkg/tlpostcode/`  which does for example the check for OS and platform and then only `lipo`  and `copy`.  In the package file `biber.tlpobj`
you need only the line

```
postaction script file=tlpkg/tlpostcode/biber.pl
```

to execute the postcode.

**Comment by plk** [comment] 2023-04-23 15:03
@hvoss49 - I'm not sure about this - if `lipo` isn't installed, which it isn't guaranteed to be unfortunately, without installing the MacOS dev tools, it would throw an error in the TL install process which might be worse than just throwing an error when running `biber` ...

**Comment by hvoss49** [comment] 2023-04-24 10:59
True, but isn't `lipo` not used if I run `biber` to get the correct version?

**Comment by plk** [comment] 2023-04-24 13:17
`lipo` is only used if the unpacked `biber` (i.e. first run of new `biber`) is a universal binary with more than one arch inside, which would be the case after a TL install.

**Comment by fyemath** [comment] 2023-06-05 16:20
I had the same error. After searching online, the solution for me is to install the xcode command line tools by running `xcode-select --install` in terminal.

**Comment by plk** [comment] 2023-07-31 11:39
Closing this for now as we have documented workarounds.

**Closed as completed by plk** 2023-07-31 11:39 UTC
