### ISSUE TITLE
encoding of copied field is wrong if new entries are created

### ISSUE THREAD

**Issue by u-fischer** [plk/biber#292] opened 2019-10-22 09:41 UTC
I'm trying to create copies of entries and get wrong encoding in the copied fields:

~~~~
\begin{filecontents}[overwrite]{test.bib}
@article{entry,
author={Max Muster},
title={Verhältnis von A und B}
}
\end{filecontents}
\documentclass{article}
\usepackage{biblatex}
\addbibresource{test.bib}
\DeclareSourcemap{
  \maps[datatype=bibtex]{
   \map{
      \step[fieldsource=title]
      \step[fieldset=titleaddon, origfieldval]
      \step[fieldsource=entrykey, match=\regexp{(.*)}]
      \step[entrynew=copy-$1, entrynewtype=misc]
      \step[fieldsource=title]
      \step[fieldset=title, origfieldval, entrytarget=copy-$1]
      }
  }
}
\begin{document}
\nocite{*}
\printbibliography[type=article]

\printbibliography[type=misc]

\end{document}
~~~~

The copy of title to titleaddon in the same entry is fine:

~~~~
      \field{title}{Verhältnis von A und B}
      \field{titleaddon}{Verhältnis von A und B}
~~~~

but the title in the new entry is wrong:

~~~~
   \field{title}{VerhÃ¤ltnis von A und B}
~~~~

and I get an inputenc error:

~~~~
! Package inputenc Error: Unicode character ¤ (U+00A4)
~~~~

**Comment by plk** [comment] 2019-10-22 13:47
Is that the full MWE? I can't reproduce this with lualatex or pdflatex, with or without inputenc (utf8) loaded - it turns out fine for me? I can see in the code a potential place where I might have to check the encoding for the `entrynew` functionality but I can't get it to fail currently ...

**Comment by u-fischer** [comment] 2019-10-22 14:16
Yes it is the full example. The engine shouldn't matter: the bib is utf8 and the bcf ascii, and these are the only files biber sees.  But my OS could matter: I'm on windows. The biber version  is 2.13 and I have the problem in texlive and miktex.

**Comment by plk** [comment] 2019-10-22 16:39
I was wondering, as you mentioned inputenc. I will see if I can reproduce this on Windows.

**Comment by moewew** [comment] 2019-10-22 19:18
I managed to reproduce the issue Ulrike describes with MikTeX on Windows as well as TeX live 2019 on Ubuntu. The problem occurs with both pdfLaTeX and LuaLaTeX, but the exact symptoms are slightly different (pdfLaTeX errors and prints "VerhÃltnis von A und B.", LuaLaTeX doesn't error and prints "VerhÃ¤ltnis von A und B."), the `.bbl`s are identical through and contain (in UTF-8!)
```
    \entry{entry}{article}{}
      \name{author}{1}{}{%
        {{hash=0434b47d44686389816f29a8f8134e12}{%
           family={Muster},
           familyi={M\bibinitperiod},
           given={Max},
           giveni={M\bibinitperiod}}}%
      }
      \strng{namehash}{0434b47d44686389816f29a8f8134e12}
      \strng{fullhash}{0434b47d44686389816f29a8f8134e12}
      \strng{bibnamehash}{0434b47d44686389816f29a8f8134e12}
      \strng{authorbibnamehash}{0434b47d44686389816f29a8f8134e12}
      \strng{authornamehash}{0434b47d44686389816f29a8f8134e12}
      \strng{authorfullhash}{0434b47d44686389816f29a8f8134e12}
      \field{sortinit}{M}
      \field{sortinithash}{2e5c2f51f7fa2d957f3206819bf86dc3}
      \field{labelnamesource}{author}
      \field{labeltitlesource}{title}
      \field{title}{Verhältnis von A und B}
      \field{titleaddon}{Verhältnis von A und B}
      \true{nocite}
    \endentry
    \entry{copy-entry}{misc}{}
      \field{sortinit}{V}
      \field{sortinithash}{02432525618c08e2b03cac47c19764af}
      \field{labeltitlesource}{title}
      \field{title}{VerhÃ¤ltnis von A und B}
      \true{nocite}
    \endentry
```

**Comment by plk** [comment] 2019-10-22 19:20
I'm currently installing MikteX in a VM to reproduce.

**Comment by moewew** [comment] 2019-10-22 19:44
The MWE indeed works fine for me with Biber 2.14 (only tested on Windows, but since I could reproduce the issue both on Windows and on Ubuntu with 2.13 I'm inclined to agree that this is not an OS-specific thing.)

**Comment by plk** [comment] 2019-10-22 19:45
I can reproduce the problem and fix on OSX too.

**Comment by u-fischer** [comment] 2019-10-22 19:59
with version 2.14 the output is okay for me.

**Comment by plk** [comment] 2019-10-22 20:01
Thank you for verifying - I'll close this.

**Closed by plk** 2019-10-22 20:01 UTC
