### ISSUE TITLE
Warning if using urldate="2020/06/22"?

### ISSUE THREAD

**Issue by daleif** [plk/biber#321] opened 2020-06-22 14:32 UTC
If we set a date to say
```
urldate="22.06.2020",
```
`biber` gives a formatting warning (`Invalid format '22.06.2020' of date field 'urldate'`)

Whereas `urldate="2020/06/22` give no warning, but also no output (we only see `(visited on )` in the PDF. 

I'm wondering whether it is `biber` that should catch this and give a warning because it does not make sense, or should the various templates better check the `urldate` data and only output something when that data actually make sense.

**Comment by pcousot** [comment] 2020-06-29 01:48
I have a similar problem with date.

%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode
\documentclass{article}
\usepackage{biblatex}% biblatex 3.14
\addbibresource{\jobname.bib}
\begin{document}
\begin{filecontents}{\jobname.bib}
@book{ref1,
  author    = {Firstname Lastname},
  title     = {Title},
  publisher = {Publisher},
  edition   = 1,
  date      = 2021-01-30,
}
\end{filecontents}
\cite{ref1}
% biber 2.14 (after rm -rf `biber --cache`)
% WARN - BibTeX subsystem: /var/folders/bx/ty2039gx3z347487cgzxw1rm0000gq/T/biber_tmp_7vjI/check-bib.bib_56584.utf8, line 10, warning: undefined macro "2021-01-30"
\printbibliography
% OK but not date
\end{document}

**Comment by moewew** [comment] 2020-06-29 05:22
@pcousot That is superficially similar, but has very different causes.

You can omit the braces around a field content for a *purely* numeric content and you have to omit the braces for a macro. Since `2021-01-30` is not purely numeric, Biber thinks this is a macro and tries to resolve it. But there is no such macro, so that's the warning you get.

The solution is to use braces around the date
```latex
\documentclass{article}
\usepackage{biblatex}

\begin{filecontents}{\jobname.bib}
@book{ref1,
  author    = {Firstname Lastname},
  title     = {Title},
  publisher = {Publisher},
  edition   = 1,
  date      = {2021-01-30},
}
\end{filecontents}
\addbibresource{\jobname.bib}

\begin{document}
\cite{ref1}
\printbibliography
\end{document}
```

**Comment by moewew** [comment] 2020-06-30 18:23
For better reproducibility here is an MWE for @daleif's issue
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\begin{filecontents}[force]{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {2020/06/22},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\cite{appleby}
\printbibliography
\end{document}
```
there is **no** warning about the malformed `date`  field in the `.blg`
```
[0] Config.pm:304> INFO - This is Biber 2.14
[0] Config.pm:307> INFO - Logfile is 'dalehd.blg'
[102] biber-MSWIN64:322> INFO - === 
[163] Biber.pm:415> INFO - Reading 'dalehd.bcf'
[311] Biber.pm:943> INFO - Found 1 citekeys in bib section 0
[340] Biber.pm:4256> INFO - Processing section 0
[341] Utils.pm:75> INFO - Globbing data source 'dalehd.bib'
[381] Utils.pm:91> INFO - Globbed data source 'dalehd.bib' to dalehd.bib
[414] Biber.pm:4455> INFO - Looking for bibtex format file 'dalehd.bib' for section 0
[417] bibtex.pm:1653> INFO - LaTeX decoding ...
[426] bibtex.pm:1471> INFO - Found BibTeX data source 'dalehd.bib'
[449] UCollate.pm:68> INFO - Overriding locale 'en-GB' defaults 'variable = shifted' with 'variable = non-ignorable'
[449] UCollate.pm:68> INFO - Overriding locale 'en-GB' defaults 'normalization = NFD' with 'normalization = prenormalized'
[450] Biber.pm:4084> INFO - Sorting list 'nyt/global//global/global' of type 'entry' with template 'nyt' and locale 'en-GB'
[450] Biber.pm:4090> INFO - No sort tailoring available for locale 'en-GB'
[452] bbl.pm:652> INFO - Writing 'dalehd.bbl' with encoding 'UTF-8'
[453] bbl.pm:755> INFO - Output to dalehd.bbl
```

Compare with
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[style=authoryear, backend=biber]{biblatex}

\begin{filecontents}[force]{\jobname.bib}
@book{appleby,
  author  = {Humphrey Appleby},
  title   = {On the Importance of the Civil Service},
  date    = {22.06.2020},
}
\end{filecontents}
\addbibresource{\jobname.bib}


\begin{document}
\cite{appleby}
\printbibliography
\end{document}
```
where we get
```
[0] Config.pm:304> INFO - This is Biber 2.14
[0] Config.pm:307> INFO - Logfile is 'dalehd.blg'
[96] biber-MSWIN64:322> INFO - === 
[158] Biber.pm:415> INFO - Reading 'dalehd.bcf'
[341] Biber.pm:943> INFO - Found 1 citekeys in bib section 0
[366] Biber.pm:4256> INFO - Processing section 0
[367] Utils.pm:75> INFO - Globbing data source 'dalehd.bib'
[392] Utils.pm:91> INFO - Globbed data source 'dalehd.bib' to dalehd.bib
[423] Biber.pm:4455> INFO - Looking for bibtex format file 'dalehd.bib' for section 0
[428] bibtex.pm:1653> INFO - LaTeX decoding ...
[440] bibtex.pm:1471> INFO - Found BibTeX data source 'dalehd.bib'
[496] Utils.pm:304> WARN - Entry 'appleby' (dalehd.bib): Invalid format '22.06.2020' of date field 'date' - ignoring
[516] UCollate.pm:68> INFO - Overriding locale 'en-GB' defaults 'normalization = NFD' with 'normalization = prenormalized'
[516] UCollate.pm:68> INFO - Overriding locale 'en-GB' defaults 'variable = shifted' with 'variable = non-ignorable'
[516] Biber.pm:4084> INFO - Sorting list 'nyt/global//global/global' of type 'entry' with template 'nyt' and locale 'en-GB'
[516] Biber.pm:4090> INFO - No sort tailoring available for locale 'en-GB'
[519] bbl.pm:652> INFO - Writing 'dalehd.bbl' with encoding 'UTF-8'
[519] bbl.pm:755> INFO - Output to dalehd.bbl
[527] Biber.pm:128> INFO - WARNINGS: 1
```

I'm assuming that is because `/` is not in itself invalid in `date` fields and actually separates date ranges, so maybe this kind of fell through the cracks.

**Comment by pcousot** [comment] 2020-06-30 22:09
thanks so much!!!

**Comment by plk** [comment] 2020-07-01 11:56
This did indeed fall through the cracks - fixed in DEV.

**Comment by moewew** [comment] 2020-07-01 15:41
The test appears to be working now. Thanks.

**Closed** 2022-06-20 10:25 UTC
